##
##  Makefile -- Build procedure for mod)ucam_webauth
##  Loosely based on the Makefile Autogenerated via ``apxs -n bar -g''.
##

#   the used tools
APXS=/usr/sbin/apxs    # Use 'make .... APXS=/path/to/apxs' if elsewhere 

#   additional user defines, includes and libraries
#DEF=-Dmy_define=my_value
#INC=-Imy/include/dir
#LIB=-Lmy/lib/dir -lmylib

#   the default target

all: mod_ucam_webauth.so

#   compile the DSO file

mod_ucam_webauth.so: mod_ucam_webauth.c
	$(APXS) -c -lcrypto -Wc,-Wall $(DEF) $(INC) $(LIB) mod_ucam_webauth.c

#   install the DSO file into the Apache installation

install: all
	$(APXS) -i mod_ucam_webauth.so

# Build a distribution

dist:
	(ver=`grep '#define VERSION' mod_ucam_webauth.c |      \
	 sed -e s/\"//g | cut -d' ' -f3`; \
	 mkdir -p mod_ucam_webauth-$$ver; \
	 rm -rf mod_ucam_webauth-$$ver/*; \
	 cp `cat MANIFEST` mod_ucam_webauth-$$ver; \
	 tar zcf mod_ucam_webauth-$$ver.tar.gz mod_ucam_webauth-$$ver;\
         rm -rf mod_ucam_webauth-$$ver )

clean:
	rm -f *~ *.o *.so *.tar.gz
